// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKyZjK8wM0DOc4FapQBBx_YwpB3jqg9E',
    appId: '1:409368159968:android:29d4da0a20b91262d45285',
    messagingSenderId: '409368159968',
    projectId: 'api-calls-e9ca6',
    databaseURL: 'https://api-calls-e9ca6.firebaseio.com',
    storageBucket: 'api-calls-e9ca6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkXOBW4bQOoV9gKaic3rei70ATT1thfUg',
    appId: '1:409368159968:ios:bdb615a4c7efe920d45285',
    messagingSenderId: '409368159968',
    projectId: 'api-calls-e9ca6',
    databaseURL: 'https://api-calls-e9ca6.firebaseio.com',
    storageBucket: 'api-calls-e9ca6.appspot.com',
    iosClientId: '409368159968-sifejgueh49glcd3ub1fh7smq82urdpj.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
